[package]
name = "meow-agent"
version = "0.1.0"
edition = "2024"

[dependencies]
openai = "1"
ratatui = "0.29"
crossterm = "0.29"
tokio = { version = "1.47.1", features = ["rt-multi-thread", "macros"] }
